- name: Add an apt signing key from docker, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add an apt key by id
  ansible.builtin.apt_key:
    id: 0EBFCD88
    state: present

- name: Add specified repository into sources list for installing docker dependent packages
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Update repositories cache and install docker dependent packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: yes
