- name: install Docker - Add the GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  args:
    warn: no

- name: install Docker - Add fingerprint
  command: "{{item}}"
  args:
    warn: false
  ignore_errors: true
  with_items:
    - apt-key fingerprint 0EBFCD88

- name: Add specified repository into sources list for installing docker dependent packages
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Update repositories cache and install docker dependent packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: yes
