version: "3.9" # optional since v1.27.0
services:
  timescaledb:
    image: timescale/timescaledb:2.3.1-pg12
    container_name: tsdb
    expose:
      - 5432
    volumes:
      - "./sql:/sql"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1440"
      - "-c"
      - "shared_buffers=250MB"
