---
version: "3.7"

services:

  ingress:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: ingress
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "http://web:9090"
      MESSAGE: "Hello World"
      NAME: "Ingress"
      SERVER_TYPE: "http"
      TIMING_50_PERCENTILE: 30ms
      TIMING_90_PERCENTILE: 60ms
      TIMING_99_PERCENTILE: 90ms
      TIMING_VARIANCE: 10
    ports:
    - 9090:9090

  web:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: web
    depends_on:
      - "ingress"
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      MESSAGE: "Web response"
      NAME: "Web"
      SERVER_TYPE: "http"
      TIMING_50_PERCENTILE: 20ms
      TIMING_90_PERCENTILE: 30ms
      TIMING_99_PERCENTILE: 40ms
      TIMING_VARIANCE: 10