# Enable the experimental disks feature via environment variable, requires Vagrant >=2.2.8.
ENV["VAGRANT_EXPERIMENTAL"] = "disks"

$drbd = <<-SCRIPT
sudo yum -y --setopt=tsflags=nodocs upgrade
sudo dnf -y install https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
sudo dnf -y install drbd90-utils kmod-drbd90
sudo cp /vagrant/drbd/drbd.conf /etc/drbd.conf
sudo mkdir /mnt/drbd
SCRIPT

$docker_compose = <<-SCRIPT
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
sudo usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/centos-8"
  config.vm.box_version = "20210726.0.1"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: $docker_compose
  config.vm.provision "shell", inline: $drbd

  config.vm.define "server1" do |node|
    node.vm.hostname = "server1"
    node.vm.network "private_network", ip: "10.1.0.10", hostname: true
    node.vm.network "forwarded_port", guest: 2224, host: 2224, protocol: "tcp"
    # additional data disk, sdb
    node.vm.disk :disk, name: "data", size: "1GB"
  end

  config.vm.define "server2" do |node|
    node.vm.hostname = "server2"
    node.vm.network "private_network", ip: "10.1.0.20", hostname: true
    # additional data disk, sdb
    node.vm.disk :disk, name: "data", size: "1GB"
  end

  config.vm.define "server3" do |node|
    node.vm.hostname = "server3"
    node.vm.network "private_network", ip: "10.1.0.30", hostname: true
  end

end
