---
version: "3.7"

services:

  consul-server:
    image: hashicorp/consul:1.8.10
    container_name: consul-server
    restart: on-failure
    command: [
      "consul", "agent",
      "-config-file", "/config/config.hcl",
      "-bind", "${HOSTIP}",
      "-advertise", "${HOSTIP}",
      # with consul keygen
      "-encrypt", "vyIt2UJcg16ULc1celZnbAUu7Wm69TeWksDNTlLZ1Z0="]
    volumes:
    - "./consul:/config"
    - "/home/vagrant/consul/data:/consul/data"
    network_mode: "host"

  stateless:
    image: timescale/timescaledb:1.5.1-pg11
    container_name: stateless
    restart: on-failure
    depends_on:
      - "consul-server"
    ports:
    # only expose sidecar port
    - 0.0.0.0:21001:21001
    networks:
      vpcbr:
        ipv4_address: 169.254.2.12

  stateless_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    container_name: stateless_proxy
    restart: on-failure
    depends_on:
      - "consul-server"
      - "stateless"
    environment:
      CONSUL_HTTP_ADDR: http://169.254.1.1:8500
      CONSUL_GRPC_ADDR: 169.254.1.1:8502
      SERVICE_CONFIG: "/config/stateless_${HOSTIP}.hcl"
      CENTRAL_CONFIG: "/central_config/stateless_defaults.hcl"
      CONNECT_SIDECAR_FOR: "stateless_${HOSTIP}"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 10 &&
            consul connect envoy -admin-bind 127.0.0.1:0 -- -l debug"
    network_mode: "service:stateless"

  patroni:
    build:
      context: ./patroni/
      dockerfile: Dockerfile.timescale
    image: patroni-image
    container_name: patroni
    restart: on-failure
    depends_on:
      - "consul-server"
    ports:
      - "0.0.0.0:8008:8008"
      - "0.0.0.0:5432:5432"
      # only expose sidecar port
      - "0.0.0.0:21002:21002"
    user: postgres
    volumes:
    - "./patroni:/config"
    - "/home/vagrant/postgresql/data:/var/lib/postgresql/data"
    environment:
      PATRONI_NAME: "patroni_${HOSTIP}"
      PATRONI_RESTAPI_CONNECT_ADDRESS: ${HOSTIP}:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${HOSTIP}:5432
      PATRONI_POSTGRESQL_DATA_DIR: /var/lib/postgresql/data
      PATRONI_CONSUL_HOST: 169.254.1.1:8500
      PATRONI_CONSUL_URL: http://169.254.1.1:8500
    networks:
      vpcbr:
        ipv4_address: 169.254.3.1
  patroni_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    container_name: patroni_proxy
    restart: on-failure
    depends_on:
      - "consul-server"
      - "patroni"
    environment:
      CONSUL_HTTP_ADDR: http://169.254.1.1:8500
      CONSUL_GRPC_ADDR: 169.254.1.1:8502
      SERVICE_CONFIG: "/config/patroni_${HOSTIP}.hcl"
      CENTRAL_CONFIG: "/central_config/patroni_defaults.hcl"
      # CONNECT_SIDECAR_FOR: "pgsql"
      CONNECT_SIDECAR_FOR: "pgsql/patroni_${HOSTIP}"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 10 &&
            consul connect envoy -admin-bind 127.0.0.1:0 -- -l debug"
    network_mode: "service:patroni"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 169.254.0.0/16
        gateway: 169.254.1.1