$dockercompose = <<-SCRIPT
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
SCRIPT

$pgsqlvolume = <<-SCRIPT
sudo mkdir -p /home/vagrant/postgresql/data/
# change owner to postgres for timescaledb
sudo chown -R 70:70 /home/vagrant/postgresql/
sudo chmod -R 750 /home/vagrant/postgresql/
SCRIPT

$sshvm = <<SCRIPT
#check for private key for vm-vm communication
[ -f /vagrant/id_rsa ] || {
  ssh-keygen -t rsa -f /vagrant/id_rsa -q -N ''
}
#deploy key
[ -f /home/vagrant/.ssh/id_rsa ] || {
    cp /vagrant/id_rsa /home/vagrant/.ssh/id_rsa
    chmod 0600 /home/vagrant/.ssh/id_rsa
}
#allow ssh passwordless
grep 'vagrant@server' ~/.ssh/authorized_keys &>/dev/null || {
  cat /vagrant/id_rsa.pub >> ~/.ssh/authorized_keys
  chmod 0600 ~/.ssh/authorized_keys
}
#exclude node* from host checking
cat > ~/.ssh/config <<EOF
Host server*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
EOF
#populate /etc/hosts
grep 10.1.0.10 /etc/hosts &>/dev/null || {
    echo 10.1.0.10 server1 | sudo tee -a /etc/hosts &>/dev/null
}
grep 10.1.0.20 /etc/hosts &>/dev/null || {
    echo 10.1.0.20 server2 | sudo tee -a /etc/hosts &>/dev/null
}
grep 10.1.0.30 /etc/hosts &>/dev/null || {
    echo 10.1.0.30 server3 | sudo tee -a /etc/hosts &>/dev/null
}
grep 10.1.0.40 /etc/hosts &>/dev/null || {
    echo 10.1.0.40 server-pgbench | sudo tee -a /etc/hosts &>/dev/null
}
#end script
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/ubuntu-18.04"
  config.vm.box_version = "20210723.0.1"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: $dockercompose
  config.vm.provision "shell", inline: $pgsqlvolume
  config.vm.provision "shell", privileged: false, inline: $sshvm

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.define "server1" do |node|
    node.vm.hostname = "server1"
    node.vm.network "private_network", ip: "10.1.0.10", hostname: true
  end

  config.vm.define "server2" do |node|
    node.vm.hostname = "server2"
    node.vm.network "private_network", ip: "10.1.0.20", hostname: true
  end

  config.vm.define "server3" do |node|
    node.vm.hostname = "server3"
    node.vm.network "private_network", ip: "10.1.0.30", hostname: true
  end

  config.vm.define "server-pgbench" do |node|
    node.vm.hostname = "server-pgbench"
    node.vm.network "private_network", ip: "10.1.0.40", hostname: true
  end

end
