$dockercompose = <<-SCRIPT
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
SCRIPT

$cockpit = <<-SCRIPT
sudo apt update -y 
sudo apt install -y cockpit
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20220328.1"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: $dockercompose
  config.vm.provision "shell", inline: $cockpit

  config.vm.define "cockpit" do |node|
    node.vm.network "forwarded_port", guest: 9090, host: 9090
  end
end
