---
version: '3.7'
services:
  standalone:
    image: mongo:5.0
    ports:
      - 27017:27017
    command: mongod --dbpath /data/db --port 27017 --config /resource/mongod.yml
    volumes:
      - ./config/mongod.yml:/resource/mongod.yml
      - db-data:/data/db

volumes:
  db-data:
