ARG TSDB_VERSION=1.5.1
ARG PG_MAJOR=11
ARG LC_ALL=C.UTF-8
ARG LANG=C.UTF-8

FROM timescale/timescaledb:$TSDB_VERSION-pg$PG_MAJOR

RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY ./patroni.yml /config/patroni.yml
ENTRYPOINT ["patroni", "/config/patroni.yml"]
