---

version: "3.7"

services:

  consul-server:
    image: hashicorp/consul:1.8.10
    command: ["consul", "agent", "-config-file=/config/config.hcl", "-config-dir=/config"]
    volumes:
    - "./consul:/config"
    ports:
    - 8500:8500

  # ingress:
  #   image: nicholasjackson/fake-service:v0.21.0
  #   depends_on:
  #     - "consul-server"
  #   environment:
  #     LISTEN_ADDR: 0.0.0.0:9090
  #     UPSTREAM_URIS: "http://localhost:9091"
  #     MESSAGE: "Hello World"
  #     NAME: "Ingress"
  #     SERVER_TYPE: "http"
  #     TIMING_50_PERCENTILE: 30ms
  #     TIMING_90_PERCENTILE: 60ms
  #     TIMING_99_PERCENTILE: 90ms
  #     TIMING_VARIANCE: 10
  #     TRACING_ZIPKIN: "http://tempo:9411"
  #   ports:
  #   - "9090:9090"
  # ingress_proxy:
  #   image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
  #   depends_on:
  #     - "ingress"
  #   environment:
  #     CONSUL_HTTP_ADDR: consul-server:8500
  #     CONSUL_GRPC_ADDR: consul-server:8502
  #     SERVICE_CONFIG: /config/ingress_v1.hcl
  #     CENTRAL_CONFIG: "/central_config/ingress_defaults.hcl"
  #   volumes:
  #   - "./fake-service/service_config:/config"
  #   - "./fake-service/central_config:/central_config"
  #   command: ["consul", "connect", "envoy", "-sidecar-for", "ingress"]
  #   network_mode: "service:ingress"

  # web:
  #   image: nicholasjackson/fake-service:v0.21.0
  #   depends_on:
  #     - "consul-server"
  #   environment:
  #     LISTEN_ADDR: 0.0.0.0:9090
  #     UPSTREAM_URIS: "grpc://localhost:9091"
  #     MESSAGE: "Web response"
  #     NAME: "Web"
  #     SERVER_TYPE: "http"
  #     HTTP_CLIENT_APPEND_REQUEST: "true"
  #     TIMING_50_PERCENTILE: 20ms
  #     TIMING_90_PERCENTILE: 30ms
  #     TIMING_99_PERCENTILE: 40ms
  #     TIMING_VARIANCE: 10
  #     TRACING_ZIPKIN: "http://tempo:9411"
  # web_proxy:
  #   image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
  #   depends_on:
  #     - "web"
  #   environment:
  #     CONSUL_HTTP_ADDR: consul-server:8500
  #     CONSUL_GRPC_ADDR: consul-server:8502
  #     SERVICE_CONFIG: /config/web_v1.hcl
  #     CENTRAL_CONFIG: "/central_config/web_defaults.hcl"
  #   volumes:
  #   - "./fake-service/service_config:/config"
  #   - "./fake-service/central_config:/central_config"
  #   command: ["consul", "connect", "envoy", "-sidecar-for", "web"]
  #   network_mode: "service:web"

  # api:
  #   image: nicholasjackson/fake-service:v0.21.0
  #   depends_on:
  #     - "consul-server"
  #   environment:
  #     LISTEN_ADDR: 0.0.0.0:9090
  #     MESSAGE: "API response"
  #     NAME: "API"
  #     SERVER_TYPE: "grpc"
  #     TIMING_50_PERCENTILE: 1ms
  #     TIMING_90_PERCENTILE: 2ms
  #     TIMING_99_PERCENTILE: 3ms
  #     TIMING_VARIANCE: 10
  #     TRACING_ZIPKIN: "http://tempo:9411"
  #     ERROR_RATE: 0.2
  #     ERROR_CODE: 14
  #     ERROR_TYPE: "http_error"
  # api_proxy:
  #   image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
  #   depends_on:
  #     - "api"
  #   environment:
  #     CONSUL_HTTP_ADDR: consul-server:8500
  #     CONSUL_GRPC_ADDR: consul-server:8502
  #     SERVICE_CONFIG: /config/api_v1.hcl
  #     CENTRAL_CONFIG: "/central_config/api_defaults.hcl"
  #   volumes:
  #   - "./fake-service/service_config:/config"
  #   - "./fake-service/central_config:/central_config"
  #   command: ["consul", "connect", "envoy", "-sidecar-for", "api"]
  #   network_mode: "service:api"
