---
version: "3.7"

services:

  consul-server:
    image: hashicorp/consul:1.8.10
    container_name: consul-server
    restart: on-failure
    command: ["consul", "agent", "-config-file=/config/config.hcl", "-advertise", "${HOSTIP}"]
    volumes:
    - "./consul:/config"
    ports:
    # DNS: The DNS server (TCP and UDP)
    - 8600:8600/tcp
    - 8600:8600/udp
    # HTTP: The HTTP API (TCP Only)
    - 8500:8500
    # gRPC: The gRPC API
    - 8502:8502
    # LAN Serf: The Serf LAN port (TCP and UDP)
    - 8301:8301/tcp
    - 8301:8301/udp
    # Wan Serf: The Serf WAN port (TCP and UDP)
    - 8302:8302
    # server: Server RPC address (TCP Only)
    - 8300:8300/tcp
    networks:
      vpcbr:
        ipv4_address: ${CONSUL_SERVER_IP_ADDR}

  ingress:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: ingress
    restart: on-failure
    depends_on:
      - "consul-server"
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "http://localhost:9091"
      MESSAGE: "Hello World from ${HOSTIP}"
      NAME: "Ingress from ${HOSTIP}"
      SERVER_TYPE: "http"
      TIMING_50_PERCENTILE: 30ms
      TIMING_90_PERCENTILE: 60ms
      TIMING_99_PERCENTILE: 90ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    ports:
    - 9090:9090
    networks:
      vpcbr:
        ipv4_address: ${INGRESS_IP_ADDR}
  ingress_proxy:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    container_name: ingress_proxy
    restart: on-failure
    depends_on:
      - "ingress"
    environment:
      CONSUL_HTTP_ADDR: ${HOSTIP}:8500
      CONSUL_GRPC_ADDR: ${HOSTIP}:8502
      SERVICE_CONFIG: /config/ingress_v1.hcl
      CENTRAL_CONFIG: "/central_config/ingress_defaults.hcl"
      CONNECT_SIDECAR_FOR: "ingress-v1"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 3 &&
            consul connect envoy -- -l debug"
    network_mode: "service:ingress"

  stateless:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: stateless
    restart: on-failure
    depends_on:
      - "consul-server"
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "grpc://localhost:9091"
      MESSAGE: "Stateless response from ${HOSTIP}"
      NAME: "Stateless from ${HOSTIP}"
      SERVER_TYPE: "http"
      HTTP_CLIENT_APPEND_REQUEST: "true"
      TIMING_50_PERCENTILE: 20ms
      TIMING_90_PERCENTILE: 30ms
      TIMING_99_PERCENTILE: 40ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    networks:
      vpcbr:
        ipv4_address: ${WEB_IP_ADDR}
  stateless_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    container_name: stateless_proxy
    restart: on-failure
    depends_on:
      - "stateless"
    environment:
      CONSUL_HTTP_ADDR: ${HOSTIP}:8500
      CONSUL_GRPC_ADDR: ${HOSTIP}:8502
      SERVICE_CONFIG: /config/stateless_v1.hcl
      CENTRAL_CONFIG: "/central_config/stateless_defaults.hcl"
      CONNECT_SIDECAR_FOR: "stateless-v1"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 5 &&
            consul connect envoy -- -l debug"
    network_mode: "service:stateless"

  stateful:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: stateful
    restart: on-failure
    depends_on:
      - "consul-server"
    environment:
      LISTEN_ADDR: 0.0.0.0:6379
      MESSAGE: "Stateful response"
      NAME: "Stateful"
      SERVER_TYPE: "grpc"
      TIMING_50_PERCENTILE: 1ms
      TIMING_90_PERCENTILE: 2ms
      TIMING_99_PERCENTILE: 3ms
      TIMING_VARIANCE: 10
      # ERROR_RATE: 0.2
      # ERROR_CODE: 14
      # ERROR_TYPE: "http_error"
      TRACING_ZIPKIN: "http://jaeger:9411"
    ports:
    - 6379:6379
    networks:
      vpcbr:
        ipv4_address: ${STATEFUL_IP_ADDR}
  stateful_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    container_name: stateful_proxy
    restart: on-failure
    depends_on:
      - "stateful"
    environment:
      CONSUL_HTTP_ADDR: ${HOSTIP}:8500
      CONSUL_GRPC_ADDR: ${HOSTIP}:8502
      SERVICE_CONFIG: /config/stateful_v1.hcl
      CENTRAL_CONFIG: "/central_config/stateful_defaults.hcl"
      CONNECT_SIDECAR_FOR: "stateful-v1"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 5 &&
            consul connect envoy -- -l debug"
    network_mode: "service:stateful"

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: ${SUBNET_CIDR}
