---
version: "3.7"

services:

  consul-server:
    image: hashicorp/consul:1.8.10
    container_name: consul-server
    restart: on-failure
    command: [
      "consul", "agent",
      "-config-file", "/config/config.hcl",
      "-bind", "${HOSTIP}",
      "-advertise", "${HOSTIP}"]
    volumes:
    - "./consul:/config"
    network_mode: "host"

  ingress:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: ingress
    restart: on-failure
    depends_on:
      - "consul-server"
    dns:
      - 169.254.1.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "http://169.254.1.1:9091"
      MESSAGE: "Hello World from ${HOSTIP}"
      NAME: "Ingress from ${HOSTIP}"
      SERVER_TYPE: "http"
      TIMING_50_PERCENTILE: 30ms
      TIMING_90_PERCENTILE: 60ms
      TIMING_99_PERCENTILE: 90ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    ports:
    - 0.0.0.0:8080:9090

  ingress_proxy:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    container_name: ingress_proxy
    restart: on-failure
    depends_on:
      - "consul-server"
      - "ingress"
    dns:
      - 169.254.1.1
    environment:
      CONSUL_HTTP_ADDR: http://169.254.1.1:8500
      CONSUL_GRPC_ADDR: 169.254.1.1:8502
      SERVICE_CONFIG: /config/ingress_${HOSTIP}.hcl
      CENTRAL_CONFIG: "/central_config/ingress_defaults.hcl"
      # CONNECT_SIDECAR_FOR: "ingress-${HOSTIP}"
      CONNECT_SIDECAR_FOR: "ingress"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 3 &&
            consul connect envoy -admin-bind 127.0.0.1:0 -- -l debug"
    network_mode: "host"

  stateless:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: stateless
    restart: on-failure
    depends_on:
      - "consul-server"
    dns:
      - 169.254.1.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "grpc://169.254.1.1:9092"
      MESSAGE: "Stateless response from ${HOSTIP}"
      NAME: "Stateless from ${HOSTIP}"
      SERVER_TYPE: "http"
      HTTP_CLIENT_APPEND_REQUEST: "true"
      TIMING_50_PERCENTILE: 20ms
      TIMING_90_PERCENTILE: 30ms
      TIMING_99_PERCENTILE: 40ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    ports:
    - 169.254.1.1:8081:9090

  stateless_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    container_name: stateless_proxy
    restart: on-failure
    depends_on:
      - "consul-server"
      - "stateless"
    environment:
      CONSUL_HTTP_ADDR: http://169.254.1.1:8500
      CONSUL_GRPC_ADDR: 169.254.1.1:8502
      SERVICE_CONFIG: /config/stateless_${HOSTIP}.hcl
      CENTRAL_CONFIG: "/central_config/stateless_defaults.hcl"
      # CONNECT_SIDECAR_FOR: "stateless-${HOSTIP}"
      CONNECT_SIDECAR_FOR: "stateless"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 5 &&
            consul connect envoy -admin-bind 127.0.0.1:0 -- -l debug"
    network_mode: "host"

  stateful:
    image: nicholasjackson/fake-service:v0.21.0
    container_name: stateful
    restart: on-failure
    depends_on:
      - "consul-server"
    dns:
      - 169.254.1.1
    environment:
      LISTEN_ADDR: 0.0.0.0:6379
      MESSAGE: "Stateful response from ${HOSTIP}"
      NAME: "Stateful from ${HOSTIP}"
      SERVER_TYPE: "grpc"
      TIMING_50_PERCENTILE: 1ms
      TIMING_90_PERCENTILE: 2ms
      TIMING_99_PERCENTILE: 3ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    ports:
    - 169.254.1.1:6379:6379

  stateful_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    container_name: stateful_proxy
    restart: on-failure
    depends_on:
      - "consul-server"
      - "stateful"
    environment:
      CONSUL_HTTP_ADDR: http://169.254.1.1:8500
      CONSUL_GRPC_ADDR: 169.254.1.1:8502
      SERVICE_CONFIG: /config/stateful_${HOSTIP}.hcl
      CENTRAL_CONFIG: "/central_config/stateful_defaults.hcl"
      # CONNECT_SIDECAR_FOR: "stateful-${HOSTIP}"
      CONNECT_SIDECAR_FOR: "stateful"
    volumes:
    - "./fake-service/service_config:/config"
    - "./fake-service/central_config:/central_config"
    command: >
      sh -c "sleep 5 &&
            consul connect envoy -admin-bind 127.0.0.1:0 -- -l debug"
    network_mode: "host"

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
