$script = <<-SCRIPT
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/ubuntu-18.04"
  config.vm.box_version = "20210723.0.1"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: $script

  config.vm.define "server1" do |node|
    node.vm.hostname = "server1"
    node.vm.network "private_network", ip: "10.1.0.10", hostname: true
    node.vm.network "forwarded_port", guest: 9090, host: 9010, protocol: "tcp"
    node.vm.network "forwarded_port", guest: 8500, host: 8010, protocol: "tcp"
  end

  config.vm.define "server2" do |node|
    node.vm.hostname = "server2"
    node.vm.network "private_network", ip: "10.1.0.20", hostname: true
    node.vm.network "forwarded_port", guest: 9090, host: 9020, protocol: "tcp"
    node.vm.network "forwarded_port", guest: 8500, host: 8020, protocol: "tcp"
  end

end
