---
# ansible-playbook.yml
- name: 'Provision Image'
  hosts: all
  become: true

  tasks:
    - include: ansible_tasks/base_config.yaml
    - include: ansible_tasks/install_docker.yaml
    - include: ansible_tasks/install_docker_compose.yaml
