---
# ansible-playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Install apache httpd  (state=present is optional)
      apt:
        name: nginx
        state: present