$setup = <<-SCRIPT
sudo apt-get update -y && sudo apt-get -y install make
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision "shell", inline: $setup

  config.vm.define "cicd" do |node|
    node.vm.network "private_network", type: "dhcp"
  end
end
