---
version: "3.7"

services:

  fluentd:
    build:
      context: ./fluentd/
      dockerfile: Dockerfile
    image: fluent-image
    container_name: fluentd
    hostname: fluentd
    restart: always
    volumes:
      - ./fluentd/data:/fluentd/log
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - 127.0.0.1:24224:24224
      - 127.0.0.1:24224:24224/udp
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}/{{.ID}}"

  nginx-log-generator:
    depends_on:
      - fluentd
    image: kscarlett/nginx-log-generator
    container_name: nginx
    hostname: nginx
    restart: always
    environment:
      - RATE=10
    networks:
      vpcbr:
        ipv4_address: 10.5.0.20
  # dummy-log-generator:
  #   depends_on:
  #     - fluentd
  #   image: kscarlett/nginx-log-generator
  #   container_name: dummy
  #   hostname: dummy
  #   restart: always
  #   environment:
  #     - RATE=10
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.5.0.30

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
