---
version: "3.7"

services:

  nginx-log-generator:
    image: kscarlett/nginx-log-generator
    container_name: nginx-log-generator
    hostname: nginx-log-generator
    restart: always
    environment:
      - RATE=1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.20
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: nginx-log-generator

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
