$dockercompose = <<-SCRIPT
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
SCRIPT

$dockerconf = <<-SCRIPT
sudo cp /vagrant/docker.conf/daemon.json /etc/docker/daemon.json
sudo systemctl restart docker
SCRIPT

$installcron = <<-SCRIPT
sudo timedatectl set-ntp no
sudo crontab -l > cron_bkp
sudo echo "10 0 * * * /usr/bin/timedatectl set-time 23:10:00 >/dev/null 2>&1" >> cron_bkp
# trigger zap logger per minute
sudo echo "*/1 * * * * /usr/bin/curl -X POST 127.0.0.1:9030/log/zaplogger >/dev/null 2>&1" >> cron_bkp
sudo crontab cron_bkp
sudo rm cron_bkp
sudo /usr/bin/timedatectl set-time 23:10:00
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/ubuntu-18.04"
  config.vm.box_version = "20210723.0.1"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: $dockerconf
  config.vm.provision "shell", inline: $dockercompose
  config.vm.provision "shell", inline: $installcron

  # Provider for VirtualBox
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 1]
  end

  config.vm.define "demo" do |node|
    node.vm.network "private_network", type: "dhcp"
  end
end
