---
version: "3.7"

services:

  consul-server:
    image: hashicorp/consul:1.8.10
    container_name: consul-server
    restart: on-failure
    command: [
      "consul", "agent",
      "-config-file", "/config/config.hcl",
      "-bind", "${HOSTIP}",
      "-advertise", "${HOSTIP}",
      # with consul keygen
      "-encrypt", "vyIt2UJcg16ULc1celZnbAUu7Wm69TeWksDNTlLZ1Z0="]
    volumes:
    - ./consul:/config
    - /home/vagrant/consul/data:/consul/data
    network_mode: "host"

  stateless:
    image: docker.io/bitnami/kafka:2.5.0-debian-10-r112
    container_name: stateless
    restart: on-failure
    depends_on:
      - consul-server
      - kafka
      - zookeeper
    volumes:
      - "/vagrant:/tmp:ro"
    command: [ "sleep", "infinity" ]
    networks:
      vpcbr:
        ipv4_address: 169.254.2.12

  kafka:
    image: docker.io/bitnami/kafka:2.5.0-debian-10-r112
    container_name: kafka
    restart: on-failure
    ports:
      - "0.0.0.0:9092:9092"
      - "0.0.0.0:9093:9093"
    volumes:
      - "/home/vagrant/kafka/data:/bitnami/kafka/data"
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://${HOSTIP}:9092,INTERNAL://${HOSTIP}::9093

      ##########
      # for development with insecured communication for kafka server and client
      ##########
      # ALLOW_PLAINTEXT_LISTENER is recommended only for development.
      # - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
      ##########
      # for production with secured communication for kafka server and client
      ##########
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CLIENT_USERS=kafkaclient
      - KAFKA_CLIENT_PASSWORDS=supersecretclient

      # zookeepr configurations
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=zkclient
      - KAFKA_ZOOKEEPER_PASSWORD=supersecret
    user: root
    depends_on:
      - consul-server
      - zookeeper
    networks:
      vpcbr:
        ipv4_address: 169.254.3.1

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.4.14-debian-9-r33
    container_name: zookeeper
    restart: on-failure
    ports:
      # - "2181:2181"
      # quorumPort
      - "0.0.0.0:2888:2888"
      # electionPort
      - "0.0.0.0:3888:3888"
    volumes:
      - "/home/vagrant/zookeeper/data:/bitnami/zookeeper/data"
    environment:
      # ALLOW_ANONYMOUS_LOGIN is recommended only for development.
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_ID=${ZOO_SERVER_ID}
      - ZOO_SERVERS=${ZOO_SERVERS}
      - ZOO_SERVER_USERS=zkclient
      - ZOO_SERVER_PASSWORDS=supersecret
    user: root
    depends_on:
      - consul-server
    networks:
      vpcbr:
        ipv4_address: 169.254.3.2

  kafka-proxy:
    image: haproxy:lts-alpine
    container_name: kafka-proxy
    restart: on-failure
    depends_on:
      - "consul-server"
      - kafka
      - kafka-proxy-template
      - zookeeper
    volumes:
    - "./haproxy:/usr/local/etc/haproxy:ro"
    networks:
      vpcbr:
        ipv4_address: 169.254.2.11

  kafka-proxy-template:
    build:
      context: ./kafka-proxy-template/
      dockerfile: Dockerfile
    image: kafka-proxy-template-image
    container_name: kafka-proxy-template
    restart: on-failure
    depends_on:
      - "consul-server"
      - kafka
      - zookeeper
    volumes:
    - "./haproxy:/tmp"
    - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CONSUL_HTTP_ADDR: http://169.254.1.1:8500
      KAFKA_PORT_NUMBER: 9092
    command: >
      consul-template -template "/tmp/haproxy.ctmpl:/tmp/haproxy.cfg:docker kill -s HUP kafka-proxy"
    network_mode: "service:kafka"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 169.254.0.0/16
        gateway: 169.254.1.1