---
version: "3.7"

services:

  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd
    hostname: fluentd
    restart: always
    volumes:
    - ./data:/fluentd/log
    - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
    - 127.0.0.1:24224:24224
    - 127.0.0.1:24224:24224/udp
