FROM centos:8

ENV container=docker

RUN yum -y --setopt=tsflags=nodocs upgrade \
    && dnf -y install passwd dnf-plugin-config-manager \
    && dnf config-manager --set-enabled ha \
    && yum -y --setopt=tsflags=nodocs install pcs which curl \
    && yum -y clean all

# install docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
RUN chmod u+x /usr/bin/docker-compose

# copy pcs RA - docker-compose
COPY ./resource-agents/heartbeat/docker-compose /usr/lib/ocf/resource.d/heartbeat

RUN mkdir -p /etc/systemd/system-preset/
RUN echo 'enable pcsd.service' > /etc/systemd/system-preset/00-pcsd.preset
RUN systemctl enable pcsd

EXPOSE 2224

CMD ["/usr/lib/systemd/systemd", "--system"]
