Vagrant.configure("2") do |config|
  config.vm.box = "package.box"

  config.vm.define "cicd" do |node|
    node.vm.network "private_network", type: "dhcp"
    node.vm.synced_folder ".", "/vagrant", disabled: true
  end
end

